version: "3.5"
services:
  web:
      container_name: hahn
      build:
        context: .
        dockerfile: Dockerfile

      volumes:
        - "/front/node_modules"
        - .:/front
      ports:
        - 4200:4200
      
      restart: always
      