### STAGE 1: Build ###
FROM node:16.17.1-alpine AS build
WORKDIR /front

COPY . .

RUN yarn && yarn global add @angular/cli @angular-devkit/build-angular @angular/material 

EXPOSE 4200

WORKDIR /front

CMD [ "yarn", "start" ]






