### STAGE 1: Build ###
FROM node:16.17.1-alpine AS build
WORKDIR /front

COPY . .

RUN yarn global add @angular/cli @angular-devkit/build-angular && yarn

EXPOSE 4200

WORKDIR /front

CMD [ "yarn", "start" ]

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build front/dist/front /usr/share/nginx/html




